//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_SZBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EGZEMPLARZ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EGZEMPLARZ()
        {
            this.POZYCJA_ZAMOWIENIA = new HashSet<POZYCJA_ZAMOWIENIA>();
        }
    
        public int ID_Egzemplarza { get; set; }
        public decimal Ilosc { get; set; }
        public int ID_Produktu { get; set; }
        public int ID_Magazynu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POZYCJA_ZAMOWIENIA> POZYCJA_ZAMOWIENIA { get; set; }
        public virtual MAGAZYN MAGAZYN { get; set; }
        public virtual PRODUKT PRODUKT { get; set; }
    }
}
