//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_SZBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KONTAKT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KONTAKT()
        {
            this.KLIENT = new HashSet<KLIENT>();
            this.PRACOWNIK = new HashSet<PRACOWNIK>();
        }
    
        public int ID_Kontaktu { get; set; }
        public string Telefon_1 { get; set; }
        public string Telefon_2 { get; set; }
        public string Faks { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KLIENT> KLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRACOWNIK> PRACOWNIK { get; set; }
    }
}
