//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_SZBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POZYCJA_ZAMOWIENIA
    {
        public int ID_Pozycji_Zamowienia { get; set; }
        public bool Czy_Kupno_Od_Klienta { get; set; }
        public decimal Kwota { get; set; }
        public decimal Ilosc { get; set; }
        public int ID_Zamowienia { get; set; }
        public Nullable<int> ID_Produktu { get; set; }
        public Nullable<int> ID_Egzemplarza { get; set; }
        public int ID_Magazynu { get; set; }
    
        public virtual EGZEMPLARZ EGZEMPLARZ { get; set; }
        public virtual MAGAZYN MAGAZYN { get; set; }
        public virtual PRODUKT PRODUKT { get; set; }
        public virtual ZAMOWIENIA ZAMOWIENIA { get; set; }
    }
}
