//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_SZBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACOWNIK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRACOWNIK()
        {
            this.ZAMOWIENIA = new HashSet<ZAMOWIENIA>();
        }
    
        public int ID_Pracownika { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public System.DateTime Data_Zatrudnienia { get; set; }
        public decimal Pensja { get; set; }
        public int ID_Adresu { get; set; }
        public int ID_Kontaktu { get; set; }
    
        public virtual ADRES ADRES { get; set; }
        public virtual KONTAKT KONTAKT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZAMOWIENIA> ZAMOWIENIA { get; set; }
    }
}
