//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_SZBD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUKT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUKT()
        {
            this.EGZEMPLARZ = new HashSet<EGZEMPLARZ>();
            this.POZYCJA_ZAMOWIENIA = new HashSet<POZYCJA_ZAMOWIENIA>();
        }
    
        public int ID_Produktu { get; set; }
        public string Nazwa { get; set; }
        public decimal Cena_Kupno { get; set; }
        public decimal Cena_Sprzedaz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EGZEMPLARZ> EGZEMPLARZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POZYCJA_ZAMOWIENIA> POZYCJA_ZAMOWIENIA { get; set; }
    }
}
