//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_SZBD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projektEntities : DbContext
    {
        public projektEntities()
            : base("name=projektEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADRES> ADRES { get; set; }
        public virtual DbSet<EGZEMPLARZ> EGZEMPLARZ { get; set; }
        public virtual DbSet<KLIENT> KLIENT { get; set; }
        public virtual DbSet<KONTAKT> KONTAKT { get; set; }
        public virtual DbSet<MAGAZYN> MAGAZYN { get; set; }
        public virtual DbSet<POZYCJA_ZAMOWIENIA> POZYCJA_ZAMOWIENIA { get; set; }
        public virtual DbSet<PRACOWNIK> PRACOWNIK { get; set; }
        public virtual DbSet<PRODUKT> PRODUKT { get; set; }
        public virtual DbSet<ZAMOWIENIA> ZAMOWIENIA { get; set; }
    }
}
